version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pubchem_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pubchem_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["./run_pipeline.sh"]

volumes:
  pg_data:
